version: "3"
services:
  app:
    depends_on:
     - db
    image: socialworky/notifications-dev:${GIT_SHA}
    restart: always
    container_name: worky-notifications-dev
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${WS_PORT}:${WS_PORT}
    environment:
      SERVER_HOST: ${SERVER_HOST}
      APP_VERSION: ${APP_VERSION}
      APP_PORT: ${APP_PORT}
      WS_PORT: ${WS_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_SSL: ${DB_SSL}
      JWT_SECRET: ${JWT_SECRET}
    dns:
      - 1.1.1.1
  db:
    container_name: pnotifications-db
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - pnotifications-db:/var/lib/postgresql/data
  
volumes:
  pnotifications-db:
    external: false
  notifications-data:
    external: false
